// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa_EPAmJZlSGsllTDin14mk3xFWzWbAXA',
    appId: '1:461368027454:web:049aeca6b1981c1e5ce46f',
    messagingSenderId: '461368027454',
    projectId: 'gemini-ai-232d0',
    authDomain: 'gemini-ai-232d0.firebaseapp.com',
    storageBucket: 'gemini-ai-232d0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Ax5pP98hIItQjFPTEbA7H8ksHc7-IPI',
    appId: '1:461368027454:android:ac4f522f568ac58a5ce46f',
    messagingSenderId: '461368027454',
    projectId: 'gemini-ai-232d0',
    storageBucket: 'gemini-ai-232d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFLnRcYUX8Gqb3maxMhEYilVRLz4lzz7k',
    appId: '1:461368027454:ios:db4b6b18fb71f3555ce46f',
    messagingSenderId: '461368027454',
    projectId: 'gemini-ai-232d0',
    storageBucket: 'gemini-ai-232d0.appspot.com',
    iosBundleId: 'com.example.geminiTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFLnRcYUX8Gqb3maxMhEYilVRLz4lzz7k',
    appId: '1:461368027454:ios:db4b6b18fb71f3555ce46f',
    messagingSenderId: '461368027454',
    projectId: 'gemini-ai-232d0',
    storageBucket: 'gemini-ai-232d0.appspot.com',
    iosBundleId: 'com.example.geminiTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa_EPAmJZlSGsllTDin14mk3xFWzWbAXA',
    appId: '1:461368027454:web:d3795805165ff67d5ce46f',
    messagingSenderId: '461368027454',
    projectId: 'gemini-ai-232d0',
    authDomain: 'gemini-ai-232d0.firebaseapp.com',
    storageBucket: 'gemini-ai-232d0.appspot.com',
  );
}
